export const OTIPPEndpoints = [
  {
    baseUrl: 'sso',
    name: 'customers',
    alias: 'customers',
    api: '',
    path: 'oti/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'generatekey',
    alias: 'generatekey',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'create',
    alias: 'createCompany',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'update',
    alias: 'updateCompany',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'enabledisable',
    alias: 'changeStatus',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'view',
    alias: 'customerDetail',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'delete',
    alias: 'deleteCompany',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'stats',
    alias: 'companyStats',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'statsdownload',
    alias: 'downloadStats',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'sendinvite',
    alias: 'sendInvite',
    api: '',
    path: 'oti/customers/',
    runAt: 'onDemand',
  },

  {
    baseUrl: 'sso',
    name: 'packages',
    alias: 'packages',
    api: '',
    path: 'oti/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'create',
    alias: 'createPackage',
    api: '',
    path: 'oti/packages/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'view',
    alias: 'packageDetail',
    api: '',
    path: 'oti/packages/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'update',
    alias: 'updatePackage',
    api: '',
    path: 'oti/packages/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'delete',
    alias: 'deletePackage',
    api: '',
    path: 'oti/packages/',
    runAt: 'onDemand',
  },
  {
    baseUrl: 'sso',
    name: 'enabledisable',
    alias: 'changePackageStatus',
    api: '',
    path: 'oti/packages/',
    runAt: 'onDemand',
  },
];

export const OTIPPEndpointMapping = {
  Customers: 'customers',
  GenerateKey: 'generatekey',
  CreateCustomer: 'createCompany',
  UpdateCopmany: 'updateCompany',
  CustomerDetail: 'customerDetail',
  CustomerChangeStatus: 'changeStatus',
  DeleteCompany: 'deleteCompany',
  CompanyStats: 'companyStats',
  DownloadStats: 'downloadStats',
  SendInvite: 'sendInvite',

  Packages: 'packages',
  CreatePackage: 'createPackage',
  PackageDetail: 'packageDetail',
  UpdatePackage: 'updatePackage',
  DeletePackage: 'deletePackage',
  ChangePackageStatus: 'changePackageStatus',
};
